brew 'caskroom/cask/brew-cask'
brew 'the_silver_searcher'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'ctags'
brew 'macvim', args: ['with-lua', 'with-override-system-vim']
tap 'railwaycat/emacsmacport'
brew 'emacs-mac', args: ['with-spacemacs-icon', 'with-imagemagick']
brew 'docker-machine'
brew 'docker-compose'
cask 'iterm2'
cask 'java'
cask 'virtualbox'
cask 'trailer'
brew 'jq'
