#!/bin/sh

stow -v 2 \
  ag \
  ctags\
  git \
  gpg \
  neovim \
  ruby \
  tig \
  tmux

dotfiles=(
  spacemacs
  zshrc
)

for file in "${dotfiles[@]}"
do
  echo "[Symlink] $file"
  ln -s $HOME/.dotfiles/$file $HOME/.$file
done
