#!/bin/sh

echo "[Symlink] nvim"
  mkdir -p $HOME/.config/nvim
  ln -s $HOME/.dotfiles/nvim $HOME/.config/nvim/init.vim

echo "[Symlink] git"
  if [ ! -L $HOME/.git_template ]; then
    ln -s $HOME/.dotfiles/git_template $HOME/.git_template
  fi
  ln -s $HOME/.dotfiles/gitconfig $HOME/.gitconfig
  ln -s $HOME/.dotfiles/gitignore $HOME/.gitignore
