#!/bin/sh

stow -v 2 \
  ag \
  ctags\
  git \
  gpg \
  neovim \
  ruby \
  tig \
  tmux

if [ ! -f $HOME/.vimrc ]; then
  ln -s $HOME/.dotfiles/neovim/.config/nvim/init.vim $HOME/.vimrc
  echo "Symlinked neovim configuration to vim"
fi

dotfiles=(
  zshrc
)

for file in "${dotfiles[@]}"
do
  echo "[Symlink] $file"
  ln -s $HOME/.dotfiles/$file $HOME/.$file
done
